name: Build & Deploy static site

on:
  push:
    branches: [main]          # regen every push to main
  workflow_dispatch:          # …or run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # -- checkout ------------------------------------------------------------
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0        # needed to push back commits

    # -- Python env for render_static.py -------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  # if render_static has deps

    # -- Node env for Webpack build -----------------------------------------
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Node deps & build
      run: |
        npm ci
        python render_static.py          # ✅ static HTML
        npm run build                    # ✅ /static/dist

    # -- Commit regenerated files back to repo -------------------------------
    - name: Commit & push generated HTML
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore(ci): auto-regen static HTML"
        branch: main                     # or gh-pages
        file_pattern: |
          *.html
          static/dist/**

    # -- (optional) Publish to GitHub Pages ----------------------------------
    # - uses: actions/configure-pages@v4
    # - uses: actions/upload-pages-artifact@v3
    #   with: { path: '.' }              # root contains index.html
    # - uses: actions/deploy-pages@v4
