# .github/workflows/static-site.yml
name: Build & Deploy static site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # ---------------- Python ---------------------------------
    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt   # <-- add this file
        # or minimal: pip install Jinja2

    # ---------------- Node -----------------------------------
    - uses: actions/setup-node@v4
      with: { node-version: '20' }

    - name: Install Node deps & build
      run: |
        npm ci
        python render_static.py
        npm run build

    # --------------- Auto-commit -----------------------------
    - name: Commit & push generated HTML
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore(ci): auto-regen static HTML"
        branch: main
        file_pattern: |
          *.html
          static/dist/**
        commit_user_name: github-actions
        commit_user_email: actions@github.com
        skip_fetch: true        # faster
        # Avoid endless loop by skipping if nothing changed
        skip_clean: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
